# Generated by Django 4.2.8 on 2023-12-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoomm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_item',
        ),
    ]
