# Generated by Django 4.2.8 on 2023-12-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoomm_app', '0002_rename_order_number_order_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_item',
            new_name='order_number',
        ),
    ]
